name: trDiscordSync
version: 1.2.6
main: me.agnes.trDiscordSync.trDiscordSync
api-version: 1.13
softdepend: [PlaceholderAPI, LuckPerms]
author: Agnes
description: Discord & Minecraft Account Linking System with Booster Rewards
permissions:
  trdiscordsync.admin:
    default: op
